---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for ubunut servers
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php }}"

      state: latest
      update_cache: yes

  - name: install apache an php  for CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


